name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: dotnet build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release
#        dotnet publish -c Release -o '${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
#    - name: 'Deploy to Azure WebApp'
#      uses: azure/webapps-deploy@v2
#      with:
#        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
#        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#        package: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}
